spring.application.name=demo

spring.datasource.url=jdbc:mysql://localhost:3306/AiServicewebsite
spring.datasource.username=root
spring.datasource.password=Nikhil@2004

spring.jpa.hibernate.ddl-auto=update